### ISSUE TITLE
dll exporting the same function it imports

### ISSUE THREAD

**Issue by Trass3r** [GrammaTech/ddisasm#50]
Did a quick test on a proxy dll, it struggled a bit with the import and export having the same name and produced:
```s
EXTERN __imp__DirectDrawCreate_disambig_0_0:PROC
EXTERN _DirectDrawCreate_disambig_0_0:PROC
```
And when fixing that and rebuilding the dll the export is
```
DirectDrawCreate_disambig_0x100075d0_0
```

ddisasm 1.5.4 (7026bf2b 2022-07-07)
invoked like
```sh
ddisasm --asm d.asm --generate-import-libs ..\d.dll
ml /nologo /c /Zi d.asm
link /nologo /DLL /ENTRY:_EntryPoint /SUBSYSTEM:windows /DEBUG /OPT:REF /OPT:ICF d.obj
```

**Comment by aeflores** [comment]
Interesting, the `_disambig_` is added by the pretty printer to avoid having multiple symbols with the same name. It sounds we should be making an exception for the case where one of the symbols is imported, and the other is locally defined.

We will address this ASAP.

**Comment by StarGazerM** [comment]
Hi, does this issue been solved now? I tried disassemble/reassemble Python windows today, seems when disasasembling `python310.dll` I saw similar probelm.

**Comment by aeflores** [comment]
It is not solved yet, but I am looking into it now.

**Comment by aeflores** [comment]
Hi @Trass3r would you have the example that you were trying available? That would help me figure out the best approach.

@StarGazerM I am not seeing this issue in `python310.dll`, which import/export  symbol gets the `_disambig_` suffix? Can you share the specific .dll where that happens?

**Comment by Trass3r** [comment]
I guess it can be replicated by something like https://godbolt.org/z/bzdrbvdra
```cpp
extern "C"
{
__declspec(dllimport) int foo();
#pragma comment(linker, "/EXPORT:foo=_myfoo")
int myfoo() { return foo(); }
} 
```

**Comment by Trass3r** [comment]
Seems like it's partially fixed but the export still has the name with the suffix.
```asm
EXTERN __imp__DirectDrawCreate:PROC
EXTERN _DirectDrawCreate:PROC

ALIGN 16
FUN_100075d0::
_DirectDrawCreate_disambig_0x100075d0_0 PROC EXPORT
```
